### ISSUE TITLE
챌린지 조회 방식을 User의 currentChallengeId를 사용해서 조회하도록 수정

### ISSUE THREAD

**Issue by jumining** [Team-HMH/HMH-Server#134]
## What is this issue? 🚀
챌린지 조회 방식 수정

## TODO 🏃‍♀️
- [x] 달성현황 정보 불러오기 api => challenge 조회방식 변경 
- [x] 스크린타임 설정할 앱 추가 api => challenge 조회방식 변경 
- [x] 스크린타임 설정할 앱 삭제 api => challenge 조회방식 변경 
- [x] 홈 이용시간 통계 불러오기 api => challenge 조회방식 변경
