### ISSUE TITLE
deploy - prod 서버 구축

### ISSUE THREAD

**Issue by kseysh** [Team-HMH/HMH-Server#145]
## What is this issue? 🚀
prod 서버 구축을 위한 작업을 해둡니다.

## TODO 🏃‍♀️
- [ ] ci / cd workflow를 설정합니다.
- [ ] aws ec2 설정 및 codedploy 설정을 합니다.
- [ ] github secrets 설정을 합니다
