### ISSUE TITLE
feat: admin api 추가

### ISSUE THREAD

**Issue by kseysh** [Team-HMH/HMH-Server#171]
## What is this issue? 🚀
admin api를 추가합니다.
admin 기능으로는 아래와 같은 기능을 우선적으로 구현합니다.
- 유저 즉시 탈퇴
- 유저 정보 변경
- dailyChallenge 상태 변경

## TODO 🏃‍♀️
- [x] admin 유저 즉시 탈퇴 기능 추가
- [x] admin 유저 정보 변경 기능 추가
- [x] admin dailyChallenge 상태 변경 기능 추가
