### ISSUE TITLE
hotfix - api 명세서와 다른 response 수정

### ISSUE THREAD

**Issue by kseysh** [Team-HMH/HMH-Server#53]
## What is this issue? 🚀
api 명세서와 다른 response 수정

## TODO 🏃‍♀️
- [ ] access token의 만료 시간을 2일로 변경
- [ ] refresh token의 만료 시간을 2주로 변경
- [ ] api/vi/user/reissue의 http method를 post로 변경
- [ ] api 명세서와 다른 response를 api 명세서와 맞도록 수정
